### ISSUE TITLE
Possible issues to discuss and check

### ISSUE THREAD

**Issue by kauedesousa** [agrobioinfoservices/ClimMob-analysis#3]
* Maybe the overall characteristic should be always mandatory? By now the algorithm for the analysis relies on this characteristic to build the first table and summaries presented in the report. So if this characteristic is not called the algorithm will brake. 

* What happens if only one characteristic is selected or remain after filtering? I’ve tried some scenarios where it happens but I am not sure if my tests covered all possible scenarios 

* What happens if only **Man** or only **Woman** participate in the project? Solve the issue in the table that disaggregate gender summaries.

**Comment by jacobvanetten** [comment]
Yes, overall charact should be mandatory

**Comment by kauedesousa** [comment]
These were solved here https://github.com/agrobioinfoservices/ClimMob-analysis/commit/e6944e043c4ea4f979bfa0818547223ee299ceaf
